### ISSUE TITLE
Documentation Suggestion

### ISSUE THREAD

**Issue by ben3636** [thedunston/sshwireguard#3]
jq is needed as a prerequisite before the nowire configuration section when using ./wireguard-server.sh --install. It is also necessary to add an additional repo when trying to install php7.2 on the latest version of Ubuntu. Moving these prerequisites to the start of the setup portion of the wiki would make installation more streamlined and easier to follow. It could also be helpful to add a short script to setup Apache with self signed certs to fast-track the server install from scratch.

**Comment by thedunston** [comment]
Thank you for the feedback. 

Yes, I see in the documentation that I put the installation of jq after running the wireguard setup.  Thanks for catching that oversight.  It has been fixed.

I've removed the version number from the PHP install example and now let the distro get the latest version from its repository instead of having to backport.

Please let me know what you think or if you are able to run the setup again and how it behaves.

<pre>
apt install apache2 php php-ssh2 php-sqlite3 sqlite3 php-mbstring php-imagick jq
git clone https://github.com/thedunston/nowire.git
cd nowire/
HEADLESS_INSTALL=y sudo ./wireguard-server.sh --install
sudo bash nowire-setup.bash
sudo wg-quick up wg0

</pre>

**Comment by ben3636** [comment]
The updated documentation looks good!
